CREATE DATABASE YUVARAJ;
USE YUVARAJ;

CREATE TABLE CUSTOMER (
    ID INT, 
    FIRST_NAME VARCHAR(15), 
    LAST_NAME VARCHAR(15), 
    SALARY bigint, 
    PHONE_NO bigint, 
    CITY VARCHAR(15) 
);
CREATE INDEX idx_lastname ON customer (Last_Name);
select * from customer;

INSERT INTO CUSTOMER ( ID, FIRST_NAME, LAST_NAME, SALARY, PHONE_NO, CITY ) VALUES
( 1, 'ZAID', 'MOHAMMAD', 9000, 8374958574, 'RAMPURU'),
( 2, 'NAGA', 'MAHESH', 29435, 8354658573, 'RAMAVARAM'),
( 3, 'NAIK', 'YUVARAJ', 15000,9786756445, 'YALLAPURU'),
( 4, 'RAJ', 'GOUDA', 18905, 7964458574, 'KAGAL'),
( 5, 'MARYA', 'MAHA', 24537, 8374563487, 'BALLARI'),
( 6, 'GOVID', 'SURESH', 9000, 8374958574, 'PURU'),
( 7, 'ZD', 'MOHA', 16000, 8374954670, 'UK'),
( 8, 'GURU', 'HAMMAD', 89900, 87934958574, 'DODDI'),
( 9, 'RAHU', 'FUJI', 18090, 8374958574, 'RAU'),
( 10, 'ZAI', 'MOHAD', 9000, 7674958574, 'DINNE'),
( 11, 'NAM', 'MOH', 19000, 8374958454, 'RAJESHU'),
( 12, 'RUMU', 'HAJI', 150080, 8974958574, 'RAGURU'),
( 13, 'YULI', 'MD', 9000, 8374958564, 'RAMAUR'),
( 14, 'KOLI', 'SACHINE', 67000, 8374958567, 'RAJASTAN'),
( 15, 'GURULI', 'BUHRU', 29000, 6363958574, 'HACHOLI');
select count(*) from customer;


CREATE TABLE Cities (
    CityID INT PRIMARY KEY,
    CityName VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    Population INT,
    Area DECIMAL(10, 2) -- Area in square kilometers
);

-- Insert initial values into the Cities table
INSERT INTO Cities (CityID, CityName, Country, Population, Area)
VALUES 
    (1, 'New York', 'USA', 8419000, 783.8),
    (2, 'Tokyo', 'Japan', 13929000, 2191.0),
    (3, 'London', 'UK', 8982000, 1572.0),
    (4, 'Sydney', 'Australia', 5312000, 12368.0),
    (5, 'Paris', 'France', 2148000, 105.4);
SELECT * FROM CITIES;
SELECT  COUNT(*) FROM CITIES;


SELECT * FROM CUSTOMER;
SELECT MIN(SALARY) AS MIN_SALARY FROM CUSTOMER;
SELECT MAX(SALARY) AS MAX_SALARY FROM CUSTOMER;
SELECT SUM(SALARY) AS SUM_SALARY FROM CUSTOMER;
SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY, SUM(SALARY) AS SUM_SALARY, 
AVG(SALARY) AS AVG_SALARY FROM CUSTOMER;

-- UPDATE
select * from customer;

UPDATE CUSTOMER SET FIRST_NAME = 'GANGA' WHERE CITY = 'RAMPURU';
UPDATE CUSTOMER SET FIRST_NAME = 'RAMLAKSHMI' WHERE SALARY = 15000;
UPDATE CUSTOMER SET LAST_NAME = 'VIRESH' WHERE FIRST_NAME = 'MARYA';
UPDATE CUSTOMER SET LAST_NAME = 'FUJI' WHERE FIRST_NAME = 'RAMA';
UPDATE CUSTOMER SET LAST_NAME = 'HAJI' WHERE FIRST_NAME = 'GANGA';
UPDATE CUSTOMER SET FIRST_NAME = 'NAGA' WHERE PHONE_NO = 8374958574;

-- AND / OR
SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'NAGA' and LAST_NAME = 'MAHESH';
SELECT * FROM CUSTOMER WHERE LAST_NAME='GOUDA' OR CITY='RAMPURU' or city = 'ramavaram';

-- NOT / IS NOT NULL
SELECT * FROM CUSTOMER WHERE NOT FIRST_NAME = 'NAGA';
SELECT * FROM CUSTOMER WHERE  FIRST_NAME IS NOT NULL;

-- ORDER BY
SELECT * FROM CUSTOMER ORDER BY  CITY;
SELECT * FROM CUSTOMER ORDER BY FIRST_NAME DESC;

-- LIKE 
select * from CUSTOMER WHERE FIRST_NAME LIKE 'a%';
SELECT * FROM CUSTOMER WHERE LAST_NAME LIKE '%A';
SELECT * FROM CUSTOMER WHERE SALARY LIKE '%5';
SELECT * FROM CUSTOMER WHERE SALARY LIKE '9%';

------ IN 
SELECT * FROM CUSTOMER WHERE CITY IN ('YALLAPURU', 'KAGAL', 'DODDI', 'RAU');

---- BETWEEN
SELECT * FROM CUSTOMER WHERE SALARY BETWEEN 10000 AND 20000;
SELECT * FROM CUSTOMER WHERE ID BETWEEN 7 AND 10;

--- ALIAS QUERY
SELECT ID AS CUSTOMER_ID, FIRST_NAME AS NAME FROM CUSTOMER;
SELECT LAST_NAME AS L_NAMEEE, PHONE_NO AS NUMBER FROM CUSTOMER;

-- UNION
SELECT CITY FROM CUSTOMER UNION SELECT CITY FROM empolee  ORDER BY CITY;

SELECT CITY FROM CUSTOMER UNION ALL SELECT CITY FROM EMPOLEE ORDER BY CITY;

-- JOINS 
----- INNER JOIN 
SELECT LAST_NAME, PHONE_NO, CITY  FROM CUSTOMER C INNER JOIN CITIES ON C.CITY = CITIES.cityName;
SELECT * FROM CUSTOMER AS C INNER JOIN CITIES as CITIES ON C.id = CITIES.CityID;
---- LEFT OUTER JOIN
SELECT * FROM CUSTOMER AS C LEFT OUTER JOIN CITIES AS CITIES ON C.CITY = CITIES.cityName;

----- RIGHT OUTER JOIN
SELECT LAST_NAME, COUNTRY, CITY, CITYID  FROM CUSTOMER C RIGHT OUTER JOIN CITIES ON C.CITY = CITIES.cityName;
SELECT LAST_NAME, COUNTRY, CITY, CITYID  FROM CUSTOMER C RIGHT JOIN CITIES ON C.CITY = CITIES.cityName;
SELECT * FROM CUSTOMER AS C RIGHT JOIN CITIES AS CITIES ON C.CITY = CITIES.cityName;

---  FULL OUTER JOIN


--- cross join
SELECT FIRST_NAME,cityName FROM customer CROSS JOIN cities;



